#!/bin/sh

charge=$(cat /sys/class/power_supply/BAT0/capacity)
stats=$(cat /sys/class/power_supply/BAT0/status)

if [[ $charge -le 20 && $stats == "Discharging" ]]; then
    notify-send -u critical "${charge}% Battery low!!..Give me some juice!!"
fi
