#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

#Startup applications
picom --vsync &
xwallpaper --stretch $HOME/wallpapers/7.jpg &
$HOME/.config/bspwm/launch.sh &
/usr/bin/dunst &
xset s 300 &
xss-lock $HOME/.config/bspwm/screenlock.sh &
#$HOME/scripts/startup.sh

bspc monitor -d I II III IV V
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding		 28

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a st-256color desktop='^2' follow=on
#bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a Audacious desktop='^5'
bspc rule -a Pavucontrol desktop='^5' follow=on
bspc rule -a Pcmanfm desktop='^3' follow=on 
bspc rule -a Transmission-gtk desktop='^3' follow=on
bspc rule -a Code desktop='^4' follow=on
