#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

#Startup applications
picom --vsync &
xwallpaper --stretch "/home/tanveer/wall/018.png" &
dunst &
xset s 600 &
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources &
xss-lock $HOME/.config/bspwm/screenlock.sh &
$HOME/.config/bspwm/workspace 'f' &

#BSPWM configurations and rules
bspc monitor -d I II III IV
bspc config border_width         3
#bspc config border_radius	 18
bspc config window_gap           2
bspc config focused_border_color "#C01D41"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a St desktop='^2' follow=on
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a Pavucontrol desktop='^4' follow=on
bspc rule -a mpv desktop='^3' follow=on
bspc rule -a Pcmanfm desktop='^3' follow=on 
