#!/bin/sh

case "$(printf "lock\\nsuspend\\nhibernate\\nlogout\\nreboot\\npoweroff" | dmenu -sb "#ee0044" -l 10 -p "⏻ ")" in
	lock) $HOME/.config/bspwm/screenlock.sh ;;
	suspend) systemctl suspend ;;
	hibernate) systemctl hibernate ;;
	logout) bspc quit ;;
	reboot) systemctl reboot ;;
	poweroff) systemctl poweroff ;;
esac
