#!/bin/sh

if [ -z "$*" ];then
    for i in $(seq 5);do
        notify-send "$(bspc query -T -m | tr '{|}' '\n' | sed -nE 's_.*name":"([^,]*)",.*focusedNodeId":([^0]).*_<---------(Workspace \1)--------->_p;s_.*className":"([^,]*)",.*_\1_p')" -r 2 -t 1200
        sleep 1
    done
else
    bspc subscribe | while read line;do notify-send "Workspace $(printf "%s" "$line" | tr ':' '\n' | sed -nE 's/^[O|F|U](.*)/\1/p')" "$(bspc query -T -d focused | tr '{|}' '\n' | sed -nE 's_.*className":"([^,]*)",.*_\1_p')" -r 1 -t 1000;done &
fi
