#!/bin/sh

case "$(printf "lock\\nsuspend\\nhibernate\\nlogout\\nreboot\\npoweroff" | wofi -bd -p "⏻ ")" in
	lock) $HOME/.config/bspwm/screenlock.sh ;;
	suspend) systemctl suspend ;;
	hibernate) systemctl hibernate ;;
	logout) riverctl exit ;;
	reboot) systemctl reboot ;;
	poweroff) systemctl poweroff ;;
esac
